# Generated by Django 5.2.4 on 2025-07-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Canvas_Model',
            new_name='CanvasModel',
        ),
    ]
