# Generated by Django 5.2.4 on 2025-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app', '0002_rename_canvas_model_canvasmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
