# Generated by Django 5.2.5 on 2025-08-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app', '0003_alter_canvasmodel_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanvasModel',
            new_name='Pixels',
        ),
    ]
