# Generated by Django 5.2.6 on 2025-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app', '0004_rename_canvasmodel_pixels'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelChunks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_x', models.IntegerField()),
                ('chunk_y', models.IntegerField()),
                ('data', models.BinaryField()),
            ],
        ),
    ]
