# Generated by Django 5.2.6 on 2025-09-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app', '0006_populate_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelchunks',
            name='data',
            field=models.TextField(),
        ),
    ]
