services:
  public_canvas_db:
    image: postgres:15-alpine
    container_name: public_canvas_db
    env_file:
      - .env
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    networks:
      - public_canvas_network
    ports:
      - "5432:5432"

  public_canvas_redis:
    image: redis:7-alpine
    container_name: public_canvas_redis
    networks:
      - public_canvas_network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  public_canvas_backend:
    build:
      context: ./backend
    container_name: public_canvas_backend
    env_file:
      - .env
    ports:
      - "2702:2702"
    volumes:
      - ./backend:/app
    depends_on:
      - public_canvas_db
      - public_canvas_redis
    networks:
      - public_canvas_network
    command: sh -c "python manage.py makemigrations && python manage.py migrate && daphne -b 0.0.0.0 -p 2702 public_canvas.asgi:application" #  python manage.py runserver 0.0.0.0:2702

  public_canvas_frontend:
    build:
      context: ./frontend
    container_name: public_canvas_frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - public_canvas_backend
    networks:
      - public_canvas_network

networks:
  public_canvas_network:
    driver: bridge
